### PR TITLE
feat(settings): add settings page

### PR DESCRIPTION
**Pull request by ysfscream**
image

### CODE REVIEW

**Comment by ysfscream** [comment]
image

**Comment by ysfscream** [comment]
image

**Review by Kinplemelon — APPROVED** [review]

**Comment by Kinplemelon** [comment]
> image

have a little question: can add settings page after code freeze?

**Review by Kinplemelon — APPROVED** [review]

**Comment by ysfscream** [comment]
> have a little question: can we add settings page after code freeze?

@Kinplemelon YES. Don't care about what the test team and product managers or project manager will say. I think this is the right thing to do.

**Comment by ysfscream** [comment]
@Kinplemelon I will merge first.

**Comment by Kinplemelon** [comment]
> 

okk

**Pull request merged**
